### ISSUE TITLE
Show raw request and response data in the demo app

### ISSUE THREAD

**Issue by ethno2405** [KoCMoHaBTa/MHIdentityKit#2]
It would be great to be able to see all requests issued by the device for debugging purposes. Also, I would like to be able to see the response from the authorization server.
Consider adding the ability to specify a network proxy address.

**Comment by SayliS** [comment]
I need this ASAP. Thx

**Comment by KoCMoHaBTa** [comment]
As of [1.5.0](https://github.com/KoCMoHaBTa/MHIdentityKit/releases/tag/1.5.0) You can now see the token request, response and error for the respective flow and copy their values.
You can set a proxy from the system's preferences on iOS and you can observe all requests there, so no need for proxy support on the demo app.
